//// ------------------------------------------------------------------------------
////  <auto-generated>
////      This code was generated by SpecFlow (http://www.specflow.org/).
////      SpecFlow Version:1.9.0.77
////      SpecFlow Generator Version:1.9.0.0
////      Runtime Version:4.0.30319.42000
//// 
////      Changes to this file may cause incorrect behavior and will be lost if
////      the code is regenerated.
////  </auto-generated>
//// ------------------------------------------------------------------------------
//#region Designer generated code
//#pragma warning disable
//namespace TestsAPI.AcceptanceTests.Features
//{
//    using TechTalk.SpecFlow;
    
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
//    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    [NUnit.Framework.TestFixtureAttribute()]
//    [NUnit.Framework.DescriptionAttribute("League")]
//    public partial class LeagueFeature
//    {
        
//        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
//#line 1 "League.feature"
//#line hidden
        
//        [NUnit.Framework.TestFixtureSetUpAttribute()]
//        public virtual void FeatureSetup()
//        {
//            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
//            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "League", "", ProgrammingLanguage.CSharp, ((string[])(null)));
//            testRunner.OnFeatureStart(featureInfo);
//        }
        
//        [NUnit.Framework.TestFixtureTearDownAttribute()]
//        public virtual void FeatureTearDown()
//        {
//            testRunner.OnFeatureEnd();
//            testRunner = null;
//        }
        
//        [NUnit.Framework.SetUpAttribute()]
//        public virtual void TestInitialize()
//        {
//        }
        
//        [NUnit.Framework.TearDownAttribute()]
//        public virtual void ScenarioTearDown()
//        {
//            testRunner.OnScenarioEnd();
//        }
        
//        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
//        {
//            testRunner.OnScenarioStart(scenarioInfo);
//        }
        
//        public virtual void ScenarioCleanup()
//        {
//            testRunner.CollectScenarioErrors();
//        }
        
//        [NUnit.Framework.TestAttribute()]
//        [NUnit.Framework.DescriptionAttribute("Viewing league table")]
//        [NUnit.Framework.CategoryAttribute("mytag")]
//        public virtual void ViewingLeagueTable()
//        {
//            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Viewing league table", new string[] {
//                        "mytag"});
//#line 5
//this.ScenarioSetup(scenarioInfo);
//#line 6
// testRunner.Given("I make a call to the API requesting the top 10 players in the league", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
//#line 7
// testRunner.Then("the top 10 players ranked by wins are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
//#line hidden
//            this.ScenarioCleanup();
//        }
//    }
//}
//#pragma warning restore
//#endregion
